[package]
name = "vm"
version = "0.1.0"
authors = ["Lenard Pratt <striderman34@gmail.com>"]

[dependencies]
util = {path = "../util"}
byteorder = "1.2.2"

[features]
debug = []
stack = ["debug"]
# default = ["debug"]